### ISSUE TITLE
Unable to publish

### ISSUE THREAD

**Issue by hobbes7878** [The-Politico/generator-politico-embeds#17]
With error:

```
[08:55:41] 'render' errored after 6.44 s
[08:55:41] TypeError in plugin "run-sequence(publish)"
Message:
    Cannot read property 'compilation' of undefined
Stack:
TypeError: Cannot read property 'compilation' of undefined
    at DefinePlugin.apply (/Users/jmcclure/Scripts/embed_hhs-tweets/node_modules/webpack/lib/DefinePlugin.js:73:18)
    at Compiler.apply (/Users/jmcclure/Scripts/embed_hhs-tweets/node_modules/webpack-stream/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/Users/jmcclure/Scripts/embed_hhs-tweets/node_modules/webpack-stream/node_modules/webpack/lib/webpack.js:33:19)
    at Stream.<anonymous> (/Users/jmcclure/Scripts/embed_hhs-tweets/node_modules/webpack-stream/index.js:134:20)
    at _end (/Users/jmcclure/Scripts/embed_hhs-tweets/node_modules/through/index.js:65:9)
    at Stream.stream.end (/Users/jmcclure/Scripts/embed_hhs-tweets/node_modules/through/index.js:74:5)
    at module.exports (/Users/jmcclure/Scripts/embed_hhs-tweets/node_modules/webpack-stream/index.js:214:12)
    at Gulp.module.exports (/Users/jmcclure/Scripts/embed_hhs-tweets/gulp/tasks/build.js:7:11)
    at module.exports (/Users/jmcclure/Scripts/embed_hhs-tweets/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/jmcclure/Scripts/embed_hhs-tweets/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/jmcclure/Scripts/embed_hhs-tweets/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/jmcclure/Scripts/embed_hhs-tweets/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/Users/jmcclure/Scripts/embed_hhs-tweets/node_modules/run-sequence/index.js:124:15)
    at Gulp.onTaskEnd (/Users/jmcclure/Scripts/embed_hhs-tweets/node_modules/run-sequence/index.js:102:4)
    at Gulp.emit (events.js:164:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/jmcclure/Scripts/embed_hhs-tweets/node_modules/orchestrator/index.js:264:8)
```

**Comment by hobbes7878** [comment]
This was related to my having an outdated package.json. Rolling webpack back to 3.2 fixed it.
